class InterestDetails {
  static const Map<String, dynamic> interestDetails = {
    'Daily Life': [
      "Cooking",
      "Reading",
      "Walking",
      "Photography",
      "Gardening",
      "Yoga",
      "Drawing",
      "Writing",
      "Crafting",
      "Meditation",
      "Hiking",
      "Volunteering",
      "DIY Projects",
      "Singing",
      "Dancing",
      "Bird Watching",
      "Fishing",
      "Cycling",
      "Board Games",
      "Collecting"
    ],
    'Comedy': [
      "Stand-up",
      "Romantic",
      "Satire",
      "Slapstick",
      "Dark",
      "Parody",
      "Mockumentary",
      "Screwball",
      "Action",
      "Musical",
      "Black",
      "Absurdist",
      "Comedy of Manners",
      "Physical",
      "Improvisational",
      "Observational",
      "Political Satire",
      "Farce",
      "Gross-Out",
      "Spoof"
    ],
    'Entertainment': [
      'Action',
      'Comedy',
      'Drama',
      'Horror',
      'Romance',
      'Science Fiction',
      'Fantasy',
      'Mystery',
      'Thriller',
      'Animation',
      'Adventure',
      'Musical',
      'Documentary',
      'Biography',
      'Crime',
      'Family',
      'History',
      'War',
      'Western',
      'Superhero',
    ],
    'Animals': [
      "Felidae",
      "Canidae",
      "Ursidae",
      "Hominidae",
      "Cetacea",
      "Artiodactyla",
      "Rodentia",
      "Aves",
      "Reptilia",
      "Amphibia",
      "Mammalia",
      "Marsupialia",
      "Chiroptera",
      "Carnivora",
      "Perissodactyla",
      "Proboscidea",
      "Sirenia",
      "Lagomorpha",
      "Primates",
      "Artiodactyla",
    ],
    'Food': [
      "Korean",
      "Chinese",
      "Western",
      "Japanese",
      "Mexican",
      "Italian",
      "French",
      "Thai",
      "Indian",
      "Turkish",
      "Brazilian",
      "Greek",
      "Spanish",
      "Russian",
      "Vietnamese",
      "Middle Eastern",
      "African",
      "Fusion",
      "Desserts",
      "Street Food"
    ],
    'Beauty & Style': [
      "Makeup",
      "Fashion",
      "Hairstyling",
      "Skincare",
      "Beauty Tutorials",
      "Outfit Styling",
      "Nail Art",
      "Beauty Routine",
      "Accessories",
      "Beauty Blogger",
      "Beauty Influencer",
      "Beauty Tips",
      "Trendy Fashion",
      "Cosmetics Reviews",
      "Sense of Style",
      "Fitness Fashion",
      "Beauty Events",
      "Healthy Lifestyle",
      "Style Icon",
      "Beauty Industry Trends"
    ],
    'Drama': [
      "Romantic",
      "Comedy",
      "Historical",
      "Crime",
      "Legal",
      "Family",
      "Political",
      "Musical",
      "Supernatural",
      "Teen",
      "Medical",
      "War",
      "Psychological",
      "Action",
      "Melodrama",
      "Adventure",
      "Mystery",
      "Sci-Fi",
      "Thriller",
      "Fantasy"
    ],
    'Talent': [
      "Skill",
      "Ability",
      "Expertise",
      "Gift",
      "Capability",
      "Aptitude",
      "Competence",
      "Proficiency",
      "Talented",
      "Natural Ability",
      "Knack",
      "Flair",
      "Genius",
      "Craftsmanship",
      "Ingenuity",
      "Talent Show",
      "Artistry",
      "Talented Individual",
      "Creative",
      "Talent Development"
    ],
    'Sports': [
      "Athletics",
      "Football",
      "Basketball",
      "Soccer",
      "Tennis",
      "Baseball",
      "Golf",
      "Swimming",
      "Boxing",
      "Running",
      "Cycling",
      "Hockey",
      "Volleyball",
      "Rugby",
      "Wrestling",
      "Martial Arts",
      "Cricket",
      "Table Tennis",
      "Skating",
      "Badminton"
    ],
    'Music': [
      'Pop',
      'Rock',
      'Jazz',
      'Hip Hop',
      'Electronic',
      'Classical',
      'R&B',
      'Country',
      'Blues',
      'Reggae',
      'Metal',
      'Folk',
      'Indie',
      'Punk',
      'Rap',
      'Dance',
      'Soul',
      'Alternative',
      'Gospel'
    ],
  };
}
